= Bootwrap
:toc: left
:toclevels: 5
:icons: font

{empty} +

== Can't wait to build your Bootstrap page? +
<<anchor-1>> +
<<anchor-2>>

{empty} +

== Introduction
Bootwrap allows you to build a default link:https://getbootstrap.com/docs/5.0/getting-started/introduction/#starter-template[Bootstrap starter template] that can be injected with Bootstrap components (e.g. Navbar, Form, Alert, Link, Jumbotron etc.) and your own custom HTML snippets to design and customize responsive mobile-first sites with only a few lines of code.

Surely, you can reference additional CSS style sheets and Javascript code(libraries), so you can easily extend the functionality and styling of your pages to fit your specific needs.

=== Starter template
Two lines is all you need to generate an empty BootWrap container object and render an empty default starter template:
[source,php]
----
$bw = new libs\BootWrap(); // create an empty BootWrap container
echo $bw->render(); // render your Bootstrap starter template
----
The BootWrap container in this example is still empty, let's have a look at how you can inject Bootstrap components to bring your page to life!

=== Bootstrap components
Bootwrap really packs a punch with its component classes. Each component class is in fact a wrapper for a link:https://getbootstrap.com/docs/5.0/components/accordion/[Bootstrap component] footnote:[Bootstrap 5 components, unless otherwise mentioned.]

These components can be configured and injected into a BootWrap container to build your pages.

NOTE: There is one special component class: `Custom`. This is not a Bootstrap component, but allows you to inject your own HTML snippets, hardcoded or from file.

==== inject components
To follow on from the previous example, let's have a look at how you can inject a component into your Bootstrap page.

A short example to show how you can inject an alert into your Bootstrap page.

1. Build an Alert component with a text message.
2. Inject the component into a BootWrap container
3. Render page.

[source,php]
----
// build an Alert
$alert = new Alert();
$alert->build("I am a HAL 9000 computer");

// inject Alert component into a BootWrap container and render page
$bw = new BootWrap();
$bw->inject($alert);
echo $bw->render();
----

{empty} +

==== Configure components
Changing the look and feel of a component is incredibly easy. For example, if you want to change the text and background color of an Alert:

[source,php]
----
// Change the text and background color and build your Alert
$alert = new Alert();
$alert->setTxtColor('dark')->setBgColor('warning');
$alert->build("I am a HAL 9000 computer");
----
Once built, to render your Alert, inject it into a BootWrap container and invoke `BootWrap::render()`:
[source,php]
----
$bw = new BootWrap();
$bw->inject($alert);
echo $bw->render();
----
{empty} +

==== Inject components with components
Some, if not most components are themselves eligible to be injected with other components. For example, a Bootstrap Alert component could be injected with one or more Button components.

To accommodate this behavior, each component has its own `inject()` method.

There are currently no restrictions on injecting components with other components, Bootwrap allows you to freely experiment with this feature.
---

{empty} +

== Examples
{empty} +

[[anchor-1]]
=== Build an empty Bootstrap template page (starter template)

1. Build an empty BootWrap container object (default Bootstrap 5 starter template)
[source,php]
$bw = new BootWrap();

2. Render the starter template
[source,php]
echo $bw->render();

Output:
[source,html]
----
<!doctype html>
<html lang="en">
 <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap5 and 'other' CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Bootwrap</title>
 </head>
 <body>

    <header class="page-header">
	</header>

    <main class="page-body">
	</main>

    <!-- Bootstrap5 and 'other' Javascript libraries-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

 </body>
</html>
----

{empty} +

[[anchor-2]]
=== Build a Bootstrap page with a Jumbotron footnoteref:[jumbotron, Jumbotron is no longer a component in Bootstrap 5 - we have built a replica and included it in Bootwrap]

*1. Build* a jumbotron with a title saying 'Bootwrap Snazzy'
[source,php]
----
$jumbotron = new Jumbotron();
$jumbotron->build('Bootwrap Snazzy');
----
*2. Inject* the Jumbotron
[source,php]
----
$bw = new BootWrap(); // build default starter template
$bw->inject($jumbotron); // inject component
----
*3. Render* the Bootstrap page with Jumbotron
[source,php]
----
echo $bw->render(); // render page
----

Output
[source,html]
----

<!doctype html>
<html lang="en">
 <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap5 and 'other' CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>Bootwrap</title>
 </head>
 <body>

    <header class="page-header">
	</header>

    <main class="page-body">
    <div class=" bg-dark text-secondary p-3 rounded-3 m-3">
      <h1 class="display-4">BootWrap Snazzy!</h1>
      <p class="lead"></p>
      <hr class="my-4">
      <p></p>
    </div>

	</main>

    <!-- Bootstrap5 and 'other' Javascript libraries-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

 </body>
</html>
----

{empty} +

== Conclusion
{empty} +
Two code examples to show how easy it really is: +

.Create a Bootstrap starter template
. *Create an empty BootWrap container*
[source,php]
$bw = new BootWrap();

. *Render*
[source,php]
echo $bw->render();

{empty} +

.Create a Bootstrap page with a Jumbotron footnoteref:[jumbotron] that says 'BootWrap Snazzy!'
. *Build* Jumbotron
[source,php]
$jumbotron = new Jumbotron();
$jumbotron->build('BootWrap Snazzy!');

. *Inject* Jumbotron
[source,php]
$bw = new BootWrap();
$bw->inject($jumbotron); // inject component

. *Render* Bootstrap page with Jumbotron
[source,php]
echo $bw->render();

{empty} +
