<?php
/**
 * Created by Yellow Heroes
 * User: Robert
 * Date: 18/09/2018
 * Time: 15:35
 */
namespace yellowheroes\bootwrap\libs;

class Footer
{
    /**
     * Footer constructor.
     * @param BootWrap $bootWrap
     * @param array $components
     */
    public function __construct(BootWrap $bootWrap, $components = [])
    {
        /* components[0] is array with hrefs, components[1] is string 'organisation-name' */
        $copyRight = $components[0]; // string: organisation-name or company name
        $hrefs = $components[1] ?? null; // array: hrefs, hypertext links
        $bootWrap->setFooter($copyRight, $hrefs); // copyright notice is appended by default
        echo "<!-- start HTML generated by class Footer -->\n";
        echo $bootWrap->getFooter(); // also closes </body></html>
    }

}
