<?php
/**
 * Created by Yellow Heroes
 * User: Robert
 * Date: 18/09/2018
 * Time: 15:35
 */
namespace yellowheroes\bootwrap;

class Footer
{
    /**
     * Footer constructor.
     * @param BootWrap $bootWrap
     * @param array $components
     */
    public function __construct(BootWrap $bootWrap, $components = [])
    {
        /* components[0] is array with hrefs, components[1] is string 'organisation-name' */
        $hrefs = $components[0]; // array: hrefs, text-links to content
        $copyRight = $components[1]; // string: organisation-name or company name
        $bootWrap->setFooter($hrefs, $copyRight); // copyright notice is appended by default
        echo "<!-- start HTML generated by class Footer -->\n";
        echo $bootWrap->getFooter();
    }

}
