<?php
/**
 * Created by Yellow Heroes
 * User: Robert
 * Date: 18/09/2018
 * Time: 15:35
 */
namespace yellowheroes\bootwrap;

class Footer
{
    public function __construct()
    {
        $footer = new BootWrap();

        $footer->setFooter("Yellow Heroes"); // copyright notice is appended by default
        echo "<!-- start HTML generated by class Footer -->\n";
        echo $footer->getFooter();
    }

}
